<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJwpeAwr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJwpeAwr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJwpeAwr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJwpeAwr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJwpeAwr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JwpeAwr',
    'container.build_id' => 'b0638efe',
    'container.build_time' => 1551836433,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJwpeAwr');
